feat: MetricWriter
fulcrumgenomics/fgpyo pull request #123
Opened 2024-06-04 17:28 UTC by msto

Closes #88 
Closes #90 

---

I am opening a feature branch to collect a number of PRs supporting the addition of a `MetricWriter`.

- [ ] #109 
- [ ] Add a `get_header()` function
- [ ] #107

2024-07-13 19:26 UTC, nh13 submitted a review, later dismissed
Looking good so far, just a couple small things

2024-07-13 19:26 UTC, nh13 commented on fgpyo/util/metric.py
> +        Lines preceding the fieldnames will be returned in the `preamble`.
mention that leading and trailing whitespaces are ignored.

2024-07-13 19:26 UTC, nh13 commented on fgpyo/util/metric.py
> +            if line.startswith(comment_prefix) or line.strip() == "":
comment can start with a whitespace right?

2024-07-13 19:26 UTC, nh13 commented on fgpyo/util/metric.py
> +        fieldnames = line.strip().split(delimiter)
probably want to check for an empty "line" since that's what we'd get if the file was empty (good thing to add a unit test for too)

2024-07-13 19:26 UTC, nh13 commented on fgpyo/util/metric.py
> +def asdict(metric: Metric) -> Dict[str, Any]:
why not be an instance method since it only takes one argument (a Metric)?

2024-07-13 19:26 UTC, nh13 commented on fgpyo/util/tests/test_metric.py
> +def test_read_header_can_read_picard(tmp_path: Path) -> None:
add tests:
1. empty file (fails: no fieldnames)
2. file with no comment lines

2024-10-17 22:24 UTC, tfenne requested changes
Could you also replace metric.write() with an implementaiton that uses the new writer so we don't have duplicate code paths/

2024-10-17 22:24 UTC, tfenne commented on fgpyo/util/metric.py
> +        header: MetricFileHeader = metric_class._read_header(fin, delimiter=delimiter)
Do you maybe want to check that `path` is a regular path first?  What if we're asked to append to stdout?

2024-10-18 00:05 UTC, tfenne approved these changes

2024-10-21 14:06 UTC, merged