feat: add hamming and levenshtein distance functions
fulcrumgenomics/fgpyo pull request #167
Opened 2024-07-18 16:03 UTC by znorgaard

Closes #93.

This PR adds functions for calculating Hamming and Levenshtein distances between two strings.

These are included for convenience and are not the optimal solution for performing many distance calculations. In those situations you should use a C-based implementation (ex. https://pypi.org/project/Distance/).

2024-07-19 18:18 UTC, nh13 requested changes
One request to move the methods to sequence.py and a few other things, but other than that, looks good.

2024-07-19 18:18 UTC, nh13 commented on fgpyo/util/distance.py
> +"""
I would put these methods in `sequence.py`, as I think we'll want to slowly move away from having a `util` sub-module where things just get shoved.

2024-07-19 18:18 UTC, nh13 commented on fgpyo/util/distance.py
> +    Calculates hamming distance between two strings. Strings must be of equal lengths.
Mention case sensitivity

2024-07-19 18:18 UTC, nh13 commented on fgpyo/util/distance.py
> +    Calculates levenshtein distance between two strings.
ditto, case sensitivity

2024-07-19 18:18 UTC, nh13 commented on fgpyo/util/distance.py
> +ex. https://pypi.org/project/Distance/
Add to docs in sequence.py and name specific methods (hamming and levenshtein)

2024-07-22 18:01 UTC, nh13 reviewed
Any reason not to support swaps, and sub/ins/del/swap penalities?  If not, perhaps we add an issue?  

See: https://github.com/fulcrumgenomics/commons/blob/9372c5585084a1d7486c1b6036d0e06824b2c8d4/src/main/scala/com/fulcrumgenomics/commons/util/StringUtil.scala#L57

2024-07-22 18:37 UTC, znorgaard commented
> Any reason not to support swaps, and sub/ins/del/swap penalities? If not, perhaps we add an issue?
> 
> See: https://github.com/fulcrumgenomics/commons/blob/9372c5585084a1d7486c1b6036d0e06824b2c8d4/src/main/scala/com/fulcrumgenomics/commons/util/StringUtil.scala#L57

Swaps aren't part of the classic Levenshtein distance. I'd argue for an additional `damerau_levenshtein` function or a boolean `demareu` option to support swapping.

No real reason for not including penalties. that would be an easy addition in this PR if it's desirable.

2024-07-22 19:38 UTC, tfenne commented
> Any reason not to support swaps, and sub/ins/del/swap penalities? If not, perhaps we add an issue?

Let me turn that around and ask .... who has an immediate use for that?  I'd prefer not to overcomplicate things.  As @znorgaard said in the PR - these are really here for "I need a quick and simple distance function" and one should use optimized versions for other work, so I think it's probably not worth investing effort making these more feature rich.

2024-07-23 13:28 UTC, nh13 commented
Just thinking about what we have in commons:
https://github.com/fulcrumgenomics/commons/blob/9372c5585084a1d7486c1b6036d0e06824b2c8d4/src/main/scala/com/fulcrumgenomics/commons/util/StringUtil.scala#L57

As suggested, we can make a PR later.

2024-07-23 16:14 UTC, znorgaard commented
Created an issue to track additional functionality requests, #170.

2024-07-30 22:52 UTC, nh13 approved these changes
Thank-you, LGTM

2024-07-30 22:54 UTC, merged