feat: overloaded 'SeqDict.from_sam()' method to support SAM files (#176)
fulcrumgenomics/fgpyo pull request #183
Opened 2024-09-04 15:52 UTC by TimD1

- in addition to pysam SAM headers and SAM header dicts, SeqDicts can now be initialized from SAM file paths and pysam SAM files
 - added basic tests for this new functionality

2024-10-17 21:01 UTC, msto requested changes

2025-01-14 20:48 UTC, nh13 requested changes
Looking really good, nice work!  Could you fix up the one TODO and the few other very minor things?

2025-01-14 20:48 UTC, nh13 commented on fgpyo/fasta/sequence_dictionary.py
> +        if isinstance(data, pysam.AlignmentHeader):
this is begging for a structural pattern ([class pattern](https://peps.python.org/pep-0622/#class-patterns)) but I think our min python version is 3.9 :/

2025-01-14 20:48 UTC, nh13 commented on fgpyo/fasta/sequence_dictionary.py
> +    # TODO: mypy doesn't like these
FIXME

2025-01-14 20:48 UTC, nh13 commented on pyproject.toml
> +[tool.coverage.report]
Nice!

2025-01-14 20:48 UTC, nh13 commented on tests/fgpyo/fasta/test_sequence_dictionary.py
> +    alignment: pysam.AlignmentFile = reader(samfile)
use with a `with` statement so it automatically closes.

2025-01-16 14:00 UTC, TimD1 commented on fgpyo/fasta/sequence_dictionary.py
> +        if isinstance(data, pysam.AlignmentHeader):
it is, unfortunately

2025-02-20 22:14 UTC, nh13 approved these changes
LGTM, thank-you

2025-02-20 22:15 UTC, merged