fast_concat() for Metric
fulcrumgenomics/fgpyo pull request #53
Opened 2023-08-25 20:09 UTC by kockan

Intended for #46

2023-11-06 20:18 UTC, TedBrookings requested changes
This is a good submission and there's nothing strictly _wrong_ with it, but there are a few minor changes I'd like to see before merging.
1) I think that overall there would be less code maintenance if the specialized appending functions were instead rolled into the writer functions with an `append` input defaulting to False. If you disagree I'm willing to entertain push-back.
2) I want to see more detailed messages when the headers aren't correct.

2023-11-06 21:19 UTC, kockan commented on fgpyo/io/__init__.py
> +        return path.open(mode="a")
Done.

2023-11-06 21:19 UTC, kockan commented on fgpyo/io/__init__.py
> +            appender.write("\n")
Done.

2023-11-06 21:20 UTC, kockan commented on fgpyo/util/metric.py
> +        assert len(headers) > 0
Done.

2023-11-06 21:20 UTC, kockan commented on fgpyo/util/metric.py
> +            io.append_lines(path = output, lines_to_append = list(io.read_lines(input_path))[1:])
Done.

2023-11-06 21:20 UTC, kockan commented on fgpyo/util/metric.py
> +        assert len(set(headers)) == 1
Done.

2023-11-06 21:22 UTC, kockan commented
I don't believe there's anything I disagree with in this review. Looks much more elegant now. Thanks for the suggestions! Let me know if this needs any further edits.

2023-11-06 23:05 UTC, TedBrookings commented
It's nearly there, but it looks like there's a few style issues. I think you need to run `ci/check.sh`. I'm not sure why the github hooks didn't run automatically for that. Other than that it's ready.

2023-11-07 15:37 UTC, TedBrookings approved these changes
Looks great now, thanks for your contribution!
Be sure to "Squash and merge" vs the other options.

2023-11-07 15:59 UTC, tfenne commented
@TedBrookings I don't think @kockan has write permissions so you'll need to do the merge!

2023-11-07 16:09 UTC, merged